import { useMemo, useState } from "react";
import { CreditCard, Eye, History, ReceiptText, Search, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import { usePermissions } from "../auth/usePermissions";
import { CobranzaStatusBadge } from "../components/cobranza/CobranzaStatusBadge";
import { FacturacionStatusBadge } from "../components/cobranza/FacturacionStatusBadge";
import { PagoFormModal } from "../components/cobranza/PagoFormModal";
import { PagosHistoryModal } from "../components/cobranza/PagosHistoryModal";
import { PagosTrashModal } from "../components/cobranza/PagosTrashModal";
import { useCuentasPorCobrar } from "../hooks/useCobranza";
import type { CuentaCobranzaResumen, EstadoCobranza } from "../types/cobranza";
import { formatCurrency } from "../utils/formatCurrency";

export function CobrosPage() {
  const { canManage } = usePermissions();
  const { cuentas, isLoading, errorMessage, reload } = useCuentasPorCobrar();
  const [search,setSearch]=useState(""); const [estado,setEstado]=useState<EstadoCobranza|"">("");
  const [isFormOpen,setIsFormOpen]=useState(false); const [initialCotizacionId,setInitialCotizacionId]=useState<number|undefined>();
  const [historyId,setHistoryId]=useState<number|null>(null); const [isTrashOpen,setIsTrashOpen]=useState(false);
  const totals=useMemo(()=>cuentas.reduce((a,c)=>({porCobrar:a.porCobrar+c.pendiente,pagado:a.pagado+c.pagado,facturado:a.facturado+c.facturado,porFacturar:a.porFacturar+c.pendiente_facturar}),{porCobrar:0,pagado:0,facturado:0,porFacturar:0}),[cuentas]);
  const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return cuentas.filter((c)=>(!term||[c.codigo,c.cliente,c.empresa,c.proyecto_nombre??""].some((v)=>v.toLowerCase().includes(term)))&&(!estado||c.estado===estado));},[cuentas,estado,search]);
  const historyCuenta=useMemo<CuentaCobranzaResumen|null>(()=>{const c=cuentas.find((i)=>i.id===historyId);return c?{...c}:null;},[cuentas,historyId]);
  const openCreate=(id?:number)=>{setInitialCotizacionId(id);setIsFormOpen(true);};
  return <div><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-black text-[#17445A]">X Cobrar</h2><p className="text-slate-500">Facturación y cobranza son procesos independientes.</p></div>{canManage&&<div className="flex gap-3"><button type="button" onClick={()=>setIsTrashOpen(true)} className="flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-3 font-bold text-slate-600"><Trash2 size={18}/> Papelera de pagos</button><button type="button" onClick={()=>openCreate()} className="flex items-center gap-2 rounded-xl bg-[#F5822A] px-5 py-3 font-bold text-white"><CreditCard size={18}/> Registrar pago</button></div>}</div>
  <section className="mt-6 grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-4">{[["Total por cobrar",totals.porCobrar,"bg-[#17445A] text-white"],["Total facturado",totals.facturado,"border border-blue-200 bg-blue-50 text-blue-900"],["Pendiente por facturar",totals.porFacturar,"border border-amber-200 bg-amber-50 text-amber-900"],["Pagos recibidos",totals.pagado,"border border-emerald-200 bg-emerald-50 text-emerald-900"]].map(([label,value,style])=><article key={String(label)} className={`rounded-2xl p-6 shadow-sm ${style}`}><p className="text-sm font-bold opacity-75">{label}</p><h3 className="mt-2 text-3xl font-black">{formatCurrency(Number(value))}</h3></article>)}</section>
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid grid-cols-1 gap-4 md:grid-cols-[1fr_220px]"><div className="relative"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Buscar por código, cliente, empresa o proyecto..." className="w-full rounded-xl border border-slate-300 py-3 pl-11 pr-4 outline-none focus:border-[#F5822A]"/></div><select value={estado} onChange={(e)=>setEstado(e.target.value as EstadoCobranza|"")} className="rounded-xl border border-slate-300 px-4 py-3 outline-none"><option value="">Todos los estados</option><option value="PENDIENTE">Pendiente</option><option value="PARCIAL">Pago parcial</option></select></div></section>
  {errorMessage&&<div className="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 font-semibold text-red-700">{errorMessage}</div>}
  {isLoading?<section className="mt-6 rounded-2xl border border-slate-200 bg-white p-10 text-center font-semibold text-slate-500">Cargando...</section>:filtered.length===0?<section className="mt-6 rounded-2xl border border-slate-200 bg-white p-8 text-center"><h3 className="text-xl font-black text-[#17445A]">No hay saldos pendientes</h3></section>:<section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h3 className="text-lg font-black text-[#17445A]">Cuentas por cobrar</h3><p className="text-sm text-slate-500">Incluye el avance de facturación.</p></div><ReceiptText className="text-[#255F7A]"/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#E8F1F5] text-[#17445A]"><tr><th className="p-4 text-left">Cotización</th><th className="p-4 text-left">Estados</th><th className="p-4 text-right">Total</th><th className="p-4 text-right">Facturado</th><th className="p-4 text-right">Pagado</th><th className="p-4 text-right">Saldo</th><th className="p-4 text-center">Acciones</th></tr></thead><tbody>{filtered.map((c)=><tr key={c.id} className="border-t border-slate-100"><td className="p-4"><Link to={`/cotizaciones/${c.id}`} className="font-black text-[#17445A] hover:text-[#F5822A]">{c.codigo}</Link><p className="mt-1 text-sm text-slate-500">{c.cliente} · {c.empresa}</p>{c.proyecto&&<Link to={`/proyectos/${c.proyecto}`} className="mt-1 block text-xs font-bold text-[#255F7A]">{c.proyecto_nombre}</Link>}</td><td className="p-4"><div className="flex flex-col items-start gap-2"><FacturacionStatusBadge estado={c.estado_facturacion}/><CobranzaStatusBadge estado={c.estado}/><span className="text-xs text-slate-500">{c.facturas_count} factura{c.facturas_count===1?"":"s"}</span></div></td><td className="p-4 text-right font-black text-[#17445A]">{formatCurrency(c.total)}</td><td className="p-4 text-right"><p className="font-black text-blue-700">{formatCurrency(c.facturado)}</p><p className="text-xs text-slate-500">Falta {formatCurrency(c.pendiente_facturar)}</p></td><td className="p-4 text-right font-black text-emerald-700">{formatCurrency(c.pagado)}</td><td className="p-4 text-right font-black text-red-600">{formatCurrency(c.pendiente)}</td><td className="p-4"><div className="flex justify-center gap-2"><Link to={`/cotizaciones/${c.id}`} className="rounded-xl bg-[#255F7A] p-2 text-white"><Eye size={16}/></Link><button type="button" onClick={()=>setHistoryId(c.id)} className="rounded-xl bg-[#E8F1F5] p-2 text-[#255F7A]"><History size={16}/></button>{canManage&&<button type="button" onClick={()=>openCreate(c.id)} className="rounded-xl bg-[#F5822A] p-2 text-white"><CreditCard size={16}/></button>}</div></td></tr>)}</tbody></table></div></section>}
  {canManage&&isFormOpen&&<PagoFormModal cuentas={cuentas} initialCotizacionId={initialCotizacionId} onClose={()=>setIsFormOpen(false)} onSaved={()=>{setIsFormOpen(false);reload();}}/>}
  {historyCuenta&&<PagosHistoryModal cuenta={historyCuenta} cuentasPorCobrar={cuentas} onClose={()=>setHistoryId(null)} onChanged={reload}/>} {canManage&&isTrashOpen&&<PagosTrashModal onClose={()=>setIsTrashOpen(false)} onRestored={reload}/>}</div>;
}
